In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('Data_Gempa.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(x)

[['Sumatera' 874 165.0 1.0 1040]
 ['Jawa' 897 100.0 5.0 1002]
 ['Bali' 60 27.0 nan 87]
 ['Nusa Tenggara' 1047 384.0 36.0 1467]
 ['Kalimantan' 36 nan nan 36]
 ['Sulawesi' 1493 451.0 33.0 1977]
 ['Maluku' 800 365.0 32.0 1197]
 ['Papua' 581 55.0 nan 636]]


In [14]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:5])
x[:, 1:5] = imputer.transform(x[:, 1:5])

In [17]:
print(x)

[['Sumatera' 874.0 165.0 1.0 1040.0]
 ['Jawa' 897.0 100.0 5.0 1002.0]
 ['Bali' 60.0 27.0 21.4 87.0]
 ['Nusa Tenggara' 1047.0 384.0 36.0 1467.0]
 ['Kalimantan' 36.0 221.0 21.4 36.0]
 ['Sulawesi' 1493.0 451.0 33.0 1977.0]
 ['Maluku' 800.0 365.0 32.0 1197.0]
 ['Papua' 581.0 55.0 21.4 636.0]]


In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [20]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 874.0 165.0 1.0 1040.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 897.0 100.0 5.0 1002.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 60.0 27.0 21.4 87.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1047.0 384.0 36.0 1467.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 36.0 221.0 21.4 36.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1493.0 451.0 33.0 1977.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 800.0 365.0 32.0 1197.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 581.0 55.0 21.4 636.0]]


In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
print(y)

[1 1 0 1 0 1 1 1]


In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [24]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 897.0 100.0 5.0 1002.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 800.0 365.0 32.0 1197.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 874.0 165.0 1.0 1040.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 36.0 221.0 21.4 36.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1047.0 384.0 36.0 1467.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1493.0 451.0 33.0 1977.0]]


In [25]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 581.0 55.0 21.4 636.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 60.0 27.0 21.4 87.0]]


In [26]:
print(y_train)

[1 1 1 0 1 1]


In [27]:
print(y_test)

[1 0]


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] = sc.fit_transform(x_train[:, 5:])
x_test[:, 5:] =sc.transform(x_test[:, 5:])

In [29]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  0.09066249394399677 -1.4280921537788058 -1.1870767624539225
  -0.20128648399974203]
 [0.0 0.0 0.0 1.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.13387185275985927 0.6627609995437552 0.767256931829974
  0.1318184470889402]
 [0.0 0.0 0.0 0.0 0.0 0.0 -0.44721359549995787 2.2360679774997894
  0.03742239111730925 -0.9152413803223286 -1.4766076801256107
  -0.136373728197845]
 [0.0 0.0 1.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -1.9023691814376533 -0.47340071395982514 -2.5715511291196724e-16
  -1.8514370657005985]
 [0.0 0.0 0.0 0.0 1.0 0.0 -0.44721359549995787 -0.44721359549995787
  0.4378805558571762 0.8126712256310331 1.0567878495016623
  0.5930406593655771]
 [0.0 0.0 0.0 0.0 0.0 0.0 2.2360679774997894 -0.44721359549995787
  1.4702755932790297 1.3413020228861712 0.839639661247896
  1.4642381714436692]]


In [30]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 -0.44721359549995787 -0.44721359549995787
  -0.6408102231531012 -1.7831426892486746 -2.5715511291196724e-16
  -0.826498816196961]
 [1.0 0.0 0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -1.8468142915315446 -2.0040630224299263 -2.5715511291196724e-16
  -1.7643173144927895]]
